### ISSUE TITLE
Prediction Issue

### ISSUE THREAD

**Issue by myselfsrh** [yuzhimanhua/Multi-BioNER#10]
Hey, while executing "seq_wc.py" file on newly trained model KeyError (missing keys in state_dict) occured. Though, it is working fine on your pre-trained model.

![Screenshot from 2019-12-05 10-10-35](https://user-images.githubusercontent.com/48582519/70232217-efd2a180-1781-11ea-968f-f954530e7c52.png)

**Comment by cszer** [comment]
hello ,i have the same issue while training my own model(i also adapt code fro pythorch 1.1.0),you need to  ner_model.load_state_dict(checkpoint_file['state_dict'],strict=False)

**Comment by cszer** [comment]
and also dont use highways because highways split your feature vectors,and you unable to load model with this sturcture

**Comment by cszer** [comment]
i also reccomend to save all train dev and test sets after constucting dataset stage to .pkl file,because if you want to tune hyperparams it will save your time because stages with loading vectors and constructing dataset you may skip
