### ISSUE TITLE
The co-train Parameter

### ISSUE THREAD

**Issue by hantingge** [yuzhimanhua/Multi-BioNER#14]
Hi,

What does the `co_train` parameter do in train_wc.py? 

In the pre-trained model you provided, `co_train` is false.

**Comment by yuzhimanhua** [comment]
Hello,

```co_train=True``` means the LSTM-CRF model is co-trained with a language model. Please refer to the following paper:

Liu et al., Empower Sequence Labeling with Task-Aware Neural Language Model. AAAI'18.

In our model, we do not incorporate this co-training strategy.

**Comment by hantingge** [comment]
Thank you for the reply. 

So as long as I input multiple datasets, the model is trained as a MTM (Multi-task) by default. If I input only one dataset, it is (equivalent to) a Single-Task Model (LSTM-CRF). Is that correct?

**Comment by yuzhimanhua** [comment]
Yes, you are right.
