### ISSUE TITLE
Couldn't pip pytorch==0.3.1

### ISSUE THREAD

**Issue by zhongxiangboy** [yuzhimanhua/Multi-BioNER#21]
Thanks for your excellent work! While pip install pytorch==0.3.1 or torch==0.3.1, these errors came up:

ERROR: Could not find a version that satisfies the requirement pytorch==0.3.1 (from versions: 0.1.2, 1.0.2)
ERROR: No matching distribution found for pytorch==0.3.1

ERROR: Could not find a version that satisfies the requirement torch==0.3.1 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0)
ERROR: No matching distribution found for torch==0.3.1

So, could u plz provide a pytorch file which meets the require of this program?

**Comment by yuzhimanhua** [comment]
Hi, thanks for your interest in our work!

Could you try the following?
```
pip install http://download.pytorch.org/whl/cu80/torch-0.3.1-cp36-cp36m-linux_x86_64.whl
```

**Comment by zhongxiangboy** [comment]
I found that it is due to my python3.7, so when I switch to python3.6,  "pip install -r requirements"  works well. Anyway, thanks a lot!
