### ISSUE TITLE
PyTorch 0.3.1 and CUDA 10.1 were used during development?

### ISSUE THREAD

**Issue by Maxwell-ur** [yuzhimanhua/Multi-BioNER#23]
Hi:
  When I configure the environment for your code. I find that torch 0.3.1 is very old version. Its corresponding CUDA version is  8 or 9, lower than 10.1. PyTorch 0.3.1 and CUDA 10.1 doesn't seem to match?

**Comment by yuzhimanhua** [comment]
Thank you for reporting this issue!

My bad. We did several rounds of modifications on README, and there are some inconsistencies. Please use torch 0.3.1 and CUDA 9.0.

**Comment by Maxwell-ur** [comment]
ok, thanks.
