### ISSUE TITLE
seq_wc.py not working properly.

### ISSUE THREAD

**Issue by mittalsarthak** [yuzhimanhua/Multi-BioNER#4]
I am trying to use seq_wc.py to prediction using the pre-trained model provided by you but in the output file, I am not getting results. It creates 5 output files but all of them are blank. Can you help me with this?

**Comment by yuzhimanhua** [comment]
Hi,

Thank you for pointing out the bug! I find that seq_wc.py always misses the LAST sentence in the testing file. So I guess you only put one sentence in your testing file (then there will be nothing in the results)? I will try to fix it ASAP. If you would like a simple and quick fix, please just "pad" one random sentence at the end of your testing file.

Thanks,
Yu

**Comment by mittalsarthak** [comment]
Hi Yu,
I have padded the input file with a sentence but now I am  getting this error:
Traceback (most recent call last):                                              
  File "seq_wc.py", line 89, in <module>
    predictor.output_batch(ner_model, feature, fout, idx)
  File "/home/conan/experiment/exp/Multi-BioNER/model/predictor.py", line 143, in output_batch
    fout.write(self.decode_str(features[ind2], l) + '\n')
  File "/home/conan/experiment/exp/Multi-BioNER/model/predictor.py", line 46, in decode_l
    return '\n'.join(map(lambda t: t[0] + ' '+ self.r_l_map[t[1]], zip(feature, label)))
  File "/home/conan/experiment/exp/Multi-BioNER/model/predictor.py", line 46, in <lambda>
    return '\n'.join(map(lambda t: t[0] + ' '+ self.r_l_map[t[1]], zip(feature, label)))
KeyError: tensor(0)

**Comment by yuzhimanhua** [comment]
May I ask what PyTorch version you are using? This repo only supports PyTorch 0.3.

**Comment by mittalsarthak** [comment]
Hi Yu,
I am using torch 1.1.0. But I have figured out the error. In predictor.py, I have made changes in decode_l function of predict class. 

       def decode_l(self, feature, label):
           return '\n'.join(map(lambda t: t[0] + ' '+ self.r_l_map[t[1].item()], zip(feature, label)))
