### ISSUE TITLE
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces).

### ISSUE THREAD

**Issue by Crucialer** [yuzhimanhua/Multi-BioNER#8]
Hello，when I reproduce the results in your paper, I meet the following probelm:
![image](https://user-images.githubusercontent.com/40562250/70028221-07bdf000-15df-11ea-8d68-1d6f8f7200a2.png)
What can I do to solve it?

**Comment by yuzhimanhua** [comment]
Hi, thanks for raising this issue.

The errors include one line (Line 309) in crf.py

Please try to use the following line to replace 308-309:
partition = utils.switch(partition, cur_partition, mask[idx].view(bat_size, 1).expand(bat_size, self.tagset_size)).view(bat_size, -1)

Also, I am not sure whether you are using pytorch 0.4 or higher. Sorry that this repo only supports pytorch 0.3.x or lower.

**Comment by Crucialer** [comment]
I get it. Now I'm using pytorch 0.3.
But when I download the embedding from http://bio.nlplab.org/, I find the embedding is garbled and I cannot read the vector from it .
![image](https://user-images.githubusercontent.com/40562250/70373071-8c7f7580-1921-11ea-8e3e-765dc98b8a14.png)
![image](https://user-images.githubusercontent.com/40562250/70373047-71146a80-1921-11ea-8300-54597dd5fb82.png)
I don't know where I went wrong. Could the embedding from http://bio.nlplab.org/ is wrong?

**Comment by yuzhimanhua** [comment]
Seems the embedding file from http://bio.nlplab.org/ is broken now.

Please directly use data_bioner_5/wikipedia-pubmed-and-PMC-w2v.txt.

**Comment by Crucialer** [comment]
ok,I succeed now. Thank you very much for your answers.
