### ISSUE TITLE
Is there any way to run it on MacOS without Nvidia GPU? 

### ISSUE THREAD

**Issue by pikapika505** [yuzhimanhua/Multi-BioNER#9]
I installed PyTorch for MacOS. When I run ./run_lm-lstm-crf5.sh I get this:
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice' 

Does this mean that if I do not have Nvidia there is no way to run your tool?

**Comment by yuzhimanhua** [comment]
Could you try the following?

torch._C._cuda_setDevice(-1)

Also, even if you can run the code with CPU, it will be extremely slow.

**Comment by pikapika505** [comment]
torch._C._cuda_setDevice(-1) did not work for me.

But I found a server with GPU server, thank you
